name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: Check Backend Code
      run: |
        cd backend
        node -c server.js

  frontend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        VITE_API_URL: http://localhost:5001
        VITE_FIREBASE_API_KEY: test_key
        VITE_FIREBASE_AUTH_DOMAIN: test.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: test
        VITE_FIREBASE_STORAGE_BUCKET: test.appspot.com
        VITE_FIREBASE_MESSAGING_SENDER_ID: "123456"
        VITE_FIREBASE_APP_ID: test_app_id
